spring.application.name=RestaurantManager

server.port=8080


# N?u MySQL c?a b?n có m?t kh?u, hãy ?i?n vào ch? spring.datasource.password
spring.datasource.url=jdbc:mysql://localhost:3306/restaurant_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=namnguyenngoc2608@

# C?u hình Hibernate t? ??ng t?o b?ng (Magic happens here!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect